### ISSUE TITLE
feature: add footer that links to ultirequiem.com

### ISSUE THREAD

**Issue by UltiRequiem** [UltiRequiem/ulticlock#1]

**Comment by Divyansh1315** [comment]
Hey I would Like to work on this issue.

**Comment by UltiRequiem** [comment]
> Hey I would Like to work on this issue.

Hey, that would be very cool!

**Comment by UltiRequiem** [comment]
I just assigned you, if you need any help write me here or in Discord, UltiRequiem#2160

**Comment by Divyansh1315** [comment]
Sure I'll contact you once it's done.
Thank you for assigning me this issue.

**Comment by Divyansh1315** [comment]
Hey you can Check I've updated. Also I want to ask one thing that have you used React Native?

**Comment by UltiRequiem** [comment]
> Hey you can Check I've updated. Also I want to ask one thing that have you used React Native?

No, is just plain [react](https://reactjs.org) + [typescript](https://www.typescriptlang.org)

If you mean in general, yes I have, is pretty cool :)

**Comment by UltiRequiem** [comment]
😔

**Comment by Divyansh1315** [comment]
Hey I thought I'm not adding any value to your project that's why I unassigned. No need to be sad about it.
If you want help with anything you can feel free to contact me any time.

**Comment by UltiRequiem** [comment]
Is okay, if I have any other Issue similar to this that I think you can implement I will ping you

![898487211673153566](https://user-images.githubusercontent.com/71897736/152909359-b10495ec-0bb5-4988-a290-3264e4d7ec72.gif)

**Comment by Divyansh1315** [comment]
Thank you

**Comment by UltiRequiem** [comment]
Hey, @Divyansh1315 I just got some time to do this feature, I also move from react to preact. and from vanilla CSS to twind.

Check the source code if you are interested 🤗
